name: Monitoring CD

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'monitoring/**'
      - '.github/workflows/monitoring_cd.yml'

jobs:
  BuildAndPushMonitoringBundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Ensure monitoring repo exists
        run: |
          aws ecr describe-repositories --repository-names ${{ secrets.MON_ECR_REPO_NAME }} || \
          aws ecr create-repository --repository-name ${{ secrets.MON_ECR_REPO_NAME }}

      - name: Determine Image Tag
        id: tag
        run: |
          EXISTING_TAGS=$(aws ecr list-images --repository-name ${{ secrets.MON_ECR_REPO_NAME }} --region ${{ secrets.AWS_REGION }} --query 'imageIds[*].imageTag' --output text)
          VERSION_TAG="arm64-v8-v0.1"
          while echo "$EXISTING_TAGS" | grep -q "$VERSION_TAG"; do
            VERSION_NUMBER=$(echo "$VERSION_TAG" |  awk -F. '{print $NF}')
            NEXT_VERSION=$((VERSION_NUMBER + 1))
            VERSION_TAG="arm64-v8-v0.$NEXT_VERSION"
          done
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Build & push monitoring bundle
        run: |
          docker buildx create --use
          TAG=$VERSION_TAG
          docker buildx build --platform linux/arm64/v8 \
            -f monitoring/Dockerfile monitoring \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MON_ECR_REPO_NAME }}:$TAG \
            --push
          echo "MON_TAG=$TAG" >> $GITHUB_ENV
